<?php

namespace app\models;

/**
 * This is the ActiveQuery class for [[InstansiPegawai]].
 *
 * @see InstansiPegawai
 */
class InstansiPegawaiQuery extends \yii\db\ActiveQuery
{
    public function aktif()
    {
        return $this->andWhere(["instansi_pegawai.status_hapus" => 0]);
    }

    public function berlaku($tanggal = null)
    {
        if ($tanggal == null) {
            $tanggal = date('Y-m-d');
        }

        return $this->andWhere('instansi_pegawai.tanggal_mulai <= :tanggal AND instansi_pegawai.tanggal_selesai >= :tanggal',[
            ':tanggal'=>$tanggal
        ]);
    }

    public function filterByTahun($tahun)
    {
        //Tanggal mulai harus kurang dari 31 Des Tahun terkait
        $this->andWhere('instansi_pegawai.tanggal_mulai <= :akhir_tahun',[
            ':akhir_tahun' => $tahun.'-12-31'
        ]);

        //Tanggal selesai harus lebih dari 1 Jan Tahun terkait atau null
        $this->andWhere('instansi_pegawai.tanggal_selesai >= :awal_tahun',[
            ':awal_tahun' => $tahun.'-01-01'
        ]);

        return $this;

    }

    public function filterByBulanTahun($bulan=null,$tahun=null)
    {
        if($bulan==null) {
            $bulan = date('n');
        }

        if($tahun==null) {
            $tahun = date('Y');
        }

        $datetime = \DateTime::createFromFormat('Y-n-d', $tahun.'-'.$bulan.'-01');

        $tanggal = $datetime->format('Y-m-15');

        return $this->andWhere('instansi_pegawai.tanggal_mulai <= :tanggal AND instansi_pegawai.tanggal_selesai >= :tanggal',[
            ':tanggal' => $tanggal
        ]);
    }

    /**
     * @param null $db
     * @return InstansiPegawai[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}
