<?php

namespace app\models;

/**
 * This is the ActiveQuery class for [[Pegawai]].
 *
 * @see Pegawai
 */
class JabatanQuery extends \yii\db\ActiveQuery
{
    public $eselon_condition = [];


    /**
     * @param null $db
     * @return Jabatan[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     * @return Jabatan
     */
    public function one($db = null)
    {
        if ($this->eselon_condition !== []) {
            $this->andWhere(['in', 'id_eselon', $this->eselon_condition]);
        }
        /** @noinspection PhpIncompatibleReturnTypeInspection */
        return parent::one($db);
    }

}
